server:
  port: 8092 # port

spring:
  application:
    name: OrderProject
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.shop: DEBUG

root:
  path: C:/MSP/OrderProject/src/main/resources/static/
  filePath: C:/MSP/FILES/
# ??? ??? ?? ??
image:
  product:
    path: IMAGES/PRODUCT
  review:
    path: IMAGES/REVIEW
  profile:
    path: IMAGES/PROFILE